name: Check
on: [ push, pull_request ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.0

      - name: Validate Module
        env:
          AWS_REGION: 'eu-west-1'
        run: |
          terraform init -backend=false
          terraform validate
          terraform fmt -check
      - name: Validate Examples
        env:
          AWS_REGION: 'eu-west-1'
        run: |
          for example in $(find examples -maxdepth 1 -mindepth 1 -type d); do
            cd $example
            terraform init -backend=false
            terraform validate
            terraform fmt -check
            cd -
          done
